<a href="https://colab.research.google.com/github/singhShreyaCoder/Python-libraries/blob/main/ASSESMENT1(Numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
# question 1
temp = np.array([30, 32, 31, 29, 35, 36, 34, 33, 31, 30])

print("Temperature Array:")
print(temp)

# b) Display the temperature on the 5th day
print("5th day temperature:", temp[4])

# c) Display the last day temperature using negative indexing
print("Last day temperature:", temp[-1])

# d) Display temperatures from day 3 to day 7
print("Temperatures from day 3 to day 7:")
print(temp[2:7])

# e) Display temperatures greater than 33°C
print("Temperatures greater than 33°C:")
print(temp[temp > 33])

Temperature Array:
[30 32 31 29 35 36 34 33 31 30]
5th day temperature: 35
Last day temperature: 30
Temperatures from day 3 to day 7:
[31 29 35 36 34]
Temperatures greater than 33°C:
[35 36 34]


In [ ]:
#question 2
marks = np.array([
    [78, 85, 82, 90],
    [88, 79, 91, 86],
    [67, 73, 70, 75],
    [92, 88, 84, 89],
    [81, 77, 79, 83]
])

print("Marks Array:")
print(marks)

# b) Display marks of the 3rd student
print("Marks of 3rd student:")
print(marks[2])

# c) Display marks of the first two subjects for all students
print("First two subjects for all students:")
print(marks[:, :2])

# d) Display marks of the last student using negative indexing
print("Marks of last student:")
print(marks[-1])

# e) Display marks of S2 and S3
print("Marks of S2 and S3:")
print(marks[1:3])

Marks Array:
[[78 85 82 90]
 [88 79 91 86]
 [67 73 70 75]
 [92 88 84 89]
 [81 77 79 83]]
Marks of 3rd student:
[67 73 70 75]
First two subjects for all students:
[[78 85]
 [88 79]
 [67 73]
 [92 88]
 [81 77]]
Marks of last student:
[81 77 79 83]
Marks of S2 and S3:
[[88 79 91 86]
 [67 73 70 75]]


In [ ]:
#question 3
sales = np.array([
    [
        [120, 150],
        [130, 140],
        [135, 160],
        [150, 170]
    ],
    [
        [200, 210],
        [195, 205],
        [220, 230],
        [210, 225]
    ],
    [
        [95, 100],
        [110, 120],
        [105, 115],
        [130, 140]
    ]
])

print("Sales Array:")
print(sales)

# b) Display the sales data of the 2nd product
print("Sales of Product 2:")
print(sales[1])

# c) Display Region 1 sales for all products
print("Region 1 sales for all products:")
print(sales[:, :, 0])

# d) Display March sales for all products
print("March sales for all products:")
print(sales[:, 2, :])

Sales Array:
[[[120 150]
  [130 140]
  [135 160]
  [150 170]]

 [[200 210]
  [195 205]
  [220 230]
  [210 225]]

 [[ 95 100]
  [110 120]
  [105 115]
  [130 140]]]
Sales of Product 2:
[[200 210]
 [195 205]
 [220 230]
 [210 225]]
Region 1 sales for all products:
[[120 130 135 150]
 [200 195 220 210]
 [ 95 110 105 130]]
March sales for all products:
[[135 160]
 [220 230]
 [105 115]]
