<a href="https://colab.research.google.com/github/singhShreyaCoder/Python-libraries/blob/main/Assesment2(Numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Question 1: Student Marks Analysis

import numpy as np

# Student IDs
student_ids = np.array(["S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9", "S10"])

# Marks
marks = np.array([78, 85, 92, 67, 88, 45, 73, 95, 81, 60])

# 1. Find the average marks
average_marks = np.mean(marks)
print("Average Marks:", average_marks)

# 2. Find the highest and lowest marks
highest_marks = np.max(marks)
lowest_marks = np.min(marks)
print("Highest Marks:", highest_marks)
print("Lowest Marks:", lowest_marks)

# 3. Find students scoring above 80
above_80 = student_ids[marks > 80]
print("Students scoring above 80:", above_80)

# 4. Find students scoring below 50
below_50 = student_ids[marks < 50]
print("Students scoring below 50:", below_50)

# 5. Add 5 grace marks to every student using vectorized operations
grace_marks = marks + 5
print("Marks after adding 5 grace marks:", grace_marks)

Average Marks: 76.4
Highest Marks: 95
Lowest Marks: 45
Students scoring above 80: ['S2' 'S3' 'S5' 'S8' 'S9']
Students scoring below 50: ['S6']
Marks after adding 5 grace marks: [ 83  90  97  72  93  50  78 100  86  65]


In [ ]:
#Question 2: Employee Salary Management
import numpy as np

employee_ids = np.array(["E1", "E2", "E3", "E4", "E5", "E6", "E7", "E8"])
salaries = np.array([25000, 32000, 45000, 55000, 28000, 60000, 75000, 50000])

# 1. Find the average salary
average_salary = np.mean(salaries)
print("Average Salary: ₹", average_salary)

# 2. Find employees earning more than ₹50,000
high_salary = employee_ids[salaries > 50000]
print("Employees earning more than ₹50,000:", high_salary)

# 3. Increase every salary by 10%
updated_salaries = salaries * 1.10
print("Salaries after 10% increase:", updated_salaries)

# 4. Find the total salary expenditure
total_expenditure = np.sum(salaries)
print("Total Salary Expenditure: ₹", total_expenditure)

# 5. Find salaries between ₹30,000 and ₹60,000
salary_range = salaries[(salaries >= 30000) & (salaries <= 60000)]
print("Salaries between ₹30,000 and ₹60,000:", salary_range)

Average Salary: ₹ 46250.0
Employees earning more than ₹50,000: ['E4' 'E6' 'E7']
Salaries after 10% increase: [27500. 35200. 49500. 60500. 30800. 66000. 82500. 55000.]
Total Salary Expenditure: ₹ 370000
Salaries between ₹30,000 and ₹60,000: [32000 45000 55000 60000 50000]


In [ ]:
#Question 3: E-Commerce Sales Dataset
import numpy as np


sales = np.array([
    [1200, 1500, 1800, 1700, 1600, 2000, 2200],
    [1400, 1600, 1900, 2100, 1800, 2300, 2500]
])

days = np.array(["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"])

# 1. Find total sales for each week
total_sales = np.sum(sales, axis=1)
print("Total Sales for Each Week:", total_sales)

# 2. Find average daily sales
average_daily_sales = np.mean(sales, axis=0)
print("Average Daily Sales:", average_daily_sales)

# 3. Find the day with maximum sales
day_index = np.argmax(np.sum(sales, axis=0))
print("Day with Maximum Sales:", days[day_index])

# 4. Extract sales of Week 1 only
week1_sales = sales[0]
print("Week 1 Sales:", week1_sales)

# 5. Extract sales of the weekend (last two columns)
weekend_sales = sales[:, -2:]
print("Weekend Sales:\n", weekend_sales)

Total Sales for Each Week: [12000 13600]
Average Daily Sales: [1300. 1550. 1850. 1900. 1700. 2150. 2350.]
Day with Maximum Sales: Sun
Week 1 Sales: [1200 1500 1800 1700 1600 2000 2200]
Weekend Sales:
 [[2000 2200]
 [2300 2500]]


In [ ]:
#Question 4: Hospital Patient Age Analysis
import numpy as np

# Patient IDs
patient_ids = np.array(["P1", "P2", "P3", "P4", "P5", "P6",
                        "P7", "P8", "P9", "P10", "P11", "P12"])

# Ages
ages = np.array([12, 18, 25, 30, 45, 60, 72, 15, 34, 50, 28, 67])

# 1. Find the average age
average_age = np.mean(ages)
print("Average Age:", average_age)

# 2. Find all senior citizens (age >= 60)
senior_citizens = patient_ids[ages >= 60]
print("Senior Citizens:", senior_citizens)

# 3. Find all children (age < 18)
children = patient_ids[ages < 18]
print("Children:", children)

# 4. Count the number of adults (18–59)
adults_count = np.sum((ages >= 18) & (ages <= 59))
print("Number of Adults:", adults_count)

# 5. Replace ages less than 18 with 0
updated_ages = np.where(ages < 18, 0, ages)
print("Updated Ages:", updated_ages)

Average Age: 38.0
Senior Citizens: ['P6' 'P7' 'P12']
Children: ['P1' 'P8']
Number of Adults: 7
Updated Ages: [ 0 18 25 30 45 60 72  0 34 50 28 67]


In [ ]:
#Question 5: Mobile App User Dataset
import numpy as np

# User IDs
user_ids = np.array(["U1", "U2", "U3", "U4", "U5"])

# Dataset
# Columns: Age, Monthly Spending, Time on App
data = np.array([
    [21, 3000, 45],
    [25, 4500, 60],
    [19, 2000, 30],
    [35, 8000, 90],
    [42, 10000, 120]
])

# 1. Display the shape of the dataset
print("Shape of Dataset:", data.shape)

# 2. Display the number of dimensions
print("Number of Dimensions:", data.ndim)

# 3. Extract only the spending column
spending = data[:, 1]
print("Monthly Spending:", spending)

# 4. Extract only the age column
age = data[:, 0]
print("Age:", age)

# 5. Find users spending more than ₹5000
high_spenders = user_ids[spending > 5000]
print("Users spending more than ₹5000:", high_spenders)

# 6. Find users spending between ₹3000 and ₹9000
mid_spenders = user_ids[(spending >= 3000) & (spending <= 9000)]
print("Users spending between ₹3000 and ₹9000:", mid_spenders)

# 7. Find average spending
average_spending = np.mean(spending)
print("Average Spending: ₹", average_spending)

# 8. Find maximum time spent on the app
max_time = np.max(data[:, 2])
print("Maximum Time Spent on App:", max_time, "minutes/day")

Shape of Dataset: (5, 3)
Number of Dimensions: 2
Monthly Spending: [ 3000  4500  2000  8000 10000]
Age: [21 25 19 35 42]
Users spending more than ₹5000: ['U4' 'U5']
Users spending between ₹3000 and ₹9000: ['U1' 'U2' 'U4']
Average Spending: ₹ 5500.0
Maximum Time Spent on App: 120 minutes/day


In [ ]:
#Question 6: Customer Dataset Preprocessing
import numpy as np

# Customer IDs
customer_ids = np.array(["C1", "C2", "C3", "C4", "C5", "C6"])


data = np.array([
    [25, 50000, 60],
    [30, 60000, 75],
    [np.nan, 55000, 68],
    [40, np.nan, 80],
    [35, 70000, np.nan],
    [28, 52000, 65]
], dtype=float)


# Part A: Data Cleaning

# 1. Count missing values
missing_values = np.isnan(data).sum()
print("Total Missing Values:", missing_values)

# Missing values column-wise
print("Missing Values in Each Column:", np.isnan(data).sum(axis=0))

# 2. Find column means (ignoring NaN values)
column_means = np.nanmean(data, axis=0)
print("Column Means:", column_means)

# 3. Replace missing values with column means
cleaned_data = data.copy()

# Get indices of missing values
rows, cols = np.where(np.isnan(cleaned_data))

# Replace NaN with corresponding column mean
cleaned_data[rows, cols] = column_means[cols]

# 4. Display the cleaned dataset
print("\nCleaned Dataset:")
print(cleaned_data)

Total Missing Values: 3
Missing Values in Each Column: [1 1 1]
Column Means: [3.16e+01 5.74e+04 6.96e+01]

Cleaned Dataset:
[[2.50e+01 5.00e+04 6.00e+01]
 [3.00e+01 6.00e+04 7.50e+01]
 [3.16e+01 5.50e+04 6.80e+01]
 [4.00e+01 5.74e+04 8.00e+01]
 [3.50e+01 7.00e+04 6.96e+01]
 [2.80e+01 5.20e+04 6.50e+01]]


In [ ]:
import numpy as np

# Customer IDs
customer_ids = np.array(["C1", "C2", "C3", "C4", "C5", "C6"])

# Cleaned Dataset (from Part A)
# Columns: Age, Income, Spending Score
data = np.array([
    [25.0, 50000.0, 60.0],
    [30.0, 60000.0, 75.0],
    [31.6, 55000.0, 68.0],   # Age filled with mean
    [40.0, 57400.0, 80.0],   # Income filled with mean
    [35.0, 70000.0, 69.6],   # Spending Score filled with mean
    [28.0, 52000.0, 65.0]
])


# Part B: Min-Max Normalization


# Find minimum and maximum values of each column
min_values = np.min(data, axis=0)
max_values = np.max(data, axis=0)

# Apply Min-Max Scaling
normalized_data = (data - min_values) / (max_values - min_values)

print("Normalized Dataset:")
print(normalized_data)


# Part C: Standardization (Z-score)


# Calculate mean and standard deviation
mean = np.mean(data, axis=0)
std = np.std(data, axis=0)

# Apply Z-score Standardization
standardized_data = (data - mean) / std

print("\nStandardized Dataset:")
print(standardized_data)


# Verification

print("\nMean of Standardized Data:")
print(np.mean(standardized_data, axis=0))

print("\nStandard Deviation of Standardized Data:")
print(np.std(standardized_data, axis=0))

Normalized Dataset:
[[0.         0.         0.        ]
 [0.33333333 0.5        0.75      ]
 [0.44       0.25       0.4       ]
 [1.         0.37       1.        ]
 [0.66666667 1.         0.48      ]
 [0.2        0.1        0.25      ]]

Standardized Dataset:
[[-1.36051149e+00 -1.13466330e+00 -1.47779777e+00]
 [-3.29820966e-01  3.98665485e-01  8.31261247e-01]
 [ 7.32349661e-16 -3.67998910e-01 -2.46299629e-01]
 [ 1.73156007e+00  0.00000000e+00  1.60094759e+00]
 [ 7.00869553e-01  1.93199428e+00 -2.18758015e-15]
 [-7.42097174e-01 -8.27997547e-01 -7.08111433e-01]]

Mean of Standardized Data:
[ 4.99600361e-16 -1.85037171e-17 -1.46179365e-15]

Standard Deviation of Standardized Data:
[1. 1. 1.]


In [ ]:
#Q7 Online Store Customer Segmentation
import numpy as np

# Customer IDs
customer_ids = np.array(["C1", "C2", "C3", "C4", "C5", "C6"])

data = np.array([
    [22, 25000],
    [35, 55000],
    [45, 85000],
    [28, 30000],
    [50, 120000],
    [40, 75000]
], dtype=float)


# 1. Find customers earning > ₹70,000
high_income = customer_ids[data[:, 1] > 70000]
print("Customers earning more than ₹70,000:", high_income)


# 2. Find customers aged between 30 and 50

age_group = customer_ids[(data[:, 0] >= 30) & (data[:, 0] <= 50)]
print("Customers aged between 30 and 50:", age_group)


# 3. Normalize the dataset (Min-Max Scaling)
min_values = np.min(data, axis=0)
max_values = np.max(data, axis=0)

normalized_data = (data - min_values) / (max_values - min_values)

print("\nNormalized Dataset:")
print(normalized_data)


# 4. Standardize the dataset (Z-score)

mean = np.mean(data, axis=0)
std = np.std(data, axis=0)

standardized_data = (data - mean) / std

print("\nStandardized Dataset:")
print(standardized_data)

# Verify Standardization
print("\nMean of Standardized Data:")
print(np.mean(standardized_data, axis=0))

print("\nStandard Deviation of Standardized Data:")
print(np.std(standardized_data, axis=0))


# 5. Shuffle the dataset randomly

np.random.seed(42)  # For reproducible results
shuffled_data = data.copy()
np.random.shuffle(shuffled_data)

print("\nShuffled Dataset:")
print(shuffled_data)


# 6. Split into 80% Training and 20% Testing Data

split_index = int(0.8 * len(shuffled_data))

train_data = shuffled_data[:split_index]
test_data = shuffled_data[split_index:]

print("\nTraining Data:")
print(train_data)

print("\nTesting Data:")
print(test_data)

Customers earning more than ₹70,000: ['C3' 'C5' 'C6']
Customers aged between 30 and 50: ['C2' 'C3' 'C5' 'C6']

Normalized Dataset:
[[0.         0.        ]
 [0.46428571 0.31578947]
 [0.82142857 0.63157895]
 [0.21428571 0.05263158]
 [1.         1.        ]
 [0.64285714 0.52631579]]

Standardized Dataset:
[[-1.53002991 -1.21998856]
 [-0.17386704 -0.30499714]
 [ 0.86933518  0.60999428]
 [-0.90410859 -1.06748999]
 [ 1.39093628  1.67748427]
 [ 0.34773407  0.30499714]]

Mean of Standardized Data:
[ 2.68303898e-16 -1.85037171e-17]

Standard Deviation of Standardized Data:
[1. 1.]

Shuffled Dataset:
[[2.2e+01 2.5e+04]
 [3.5e+01 5.5e+04]
 [4.0e+01 7.5e+04]
 [4.5e+01 8.5e+04]
 [5.0e+01 1.2e+05]
 [2.8e+01 3.0e+04]]

Training Data:
[[2.2e+01 2.5e+04]
 [3.5e+01 5.5e+04]
 [4.0e+01 7.5e+04]
 [4.5e+01 8.5e+04]]

Testing Data:
[[5.0e+01 1.2e+05]
 [2.8e+01 3.0e+04]]
