<a href="https://colab.research.google.com/github/singhShreyaCoder/Python-libraries/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

#create a 1D array
a=np.array(["1","2","3"])
b=np.array(["shreya","utkarsh","shagun"])
print(a+b)

#check shape
print(a.shape)
print(a.dtype)
print(a.ndim)

#1D array
a1=[1,2,5,7,9,4,3,2,5,1]
print(a1[4])

a2=[
    [1,5,7,9],
    [4,3,2,7],
    [7,4,1,4]
]
print(a2[2][-2])

a3=[
    [2,4,5,5],
    [6,9,7,4],
    [1,5,7,9],
    [4,5,3,2]
]

print(a3[2][3])

['1shreya' '2utkarsh' '3shagun']
(3,)
<U1
1
9
1
9


In [ ]:

#3D Array
threeD=np.array([
    [[1,2,3,4,5],[6,7,8,9,1],[5,4,3,2,1]],

    [[7,5,2,5,3],[2,3,4,5,6],[1,2,3,4,5]]
])

print(threeD)
import numpy as np
#Day2
# Question 1. Weather report

temp=np.array([32,33,35,30,31,29,35,36,34,37])
print(temp)
print(temp[4])
print(temp[-4])
print(temp[2:-3])



#Q2.create 2D array

s1=[78,85,82,90]
s2=[88,79,91,86]
s3=[67,73,70,75]
s4=[92,88,84,89]

marks=np.array([s1,s2,s3,s4])
#Q1.create 2D array
print(marks)
#Q2.print marks of 3rd student
print([s3])
#Q3.Print marks of 3rd student using indexing
print(s2[0:4])
#4.
print([s2,s3])


#question 1
data=np.array([
    [[200,210],[195,205],[135,160],[150,170]],

    [[200,120] ,[195,205], [220,230] ,[210,225]],

    [[95,100],[110,120],[105,115],[130,140]]
])

print("sales data:\n",data)
print("sales of second product:",data[1])
print("region 1 sales:\n",data[:,:,0])
print("march sales:\n",data[:,2])


[[[1 2 3 4 5]
  [6 7 8 9 1]
  [5 4 3 2 1]]

 [[7 5 2 5 3]
  [2 3 4 5 6]
  [1 2 3 4 5]]]
[32 33 35 30 31 29 35 36 34 37]
31
35
[35 30 31 29 35]
[[78 85 82 90]
 [88 79 91 86]
 [67 73 70 75]
 [92 88 84 89]]
[[67, 73, 70, 75]]
[88, 79, 91, 86]
[[88, 79, 91, 86], [67, 73, 70, 75]]
sales data:
 [[[200 210]
  [195 205]
  [135 160]
  [150 170]]

 [[200 120]
  [195 205]
  [220 230]
  [210 225]]

 [[ 95 100]
  [110 120]
  [105 115]
  [130 140]]]
sales of second product: [[200 120]
 [195 205]
 [220 230]
 [210 225]]
region 1 sales:
 [[200 195 135 150]
 [200 195 220 210]
 [ 95 110 105 130]]
march sales:
 [[135 160]
 [220 230]
 [105 115]]


In [ ]:
import numpy as np

#mathematical operations
#add np.add(a,b)
#sub np.subtract(a,b)
#multiply np.multiply(a,b)
#divide np.divide(a,b)
#mod np.mod(a,b)
#power np.power(a,b)

a=np.array([21,23,43])
b=np.array([11,12,13])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))
print(np.power(a,b))



[32 35 56]
[10 11 30]
[231 276 559]
[1.90909091 1.91666667 3.30769231]
[10 11  4]
[    350277500542221   21914624432020321 2716925427302484955]


In [ ]:
a=np.array([
    [5,7,9],
     [4,3,2]
])

b=np.array([
    [6,7,3],
    [5,4,7]
])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))
print(np.power(a,b))


[[11 14 12]
 [ 9  7  9]]
[[-1  0  6]
 [-1 -1 -5]]
[[30 49 27]
 [20 12 14]]
[[0.83333333 1.         3.        ]
 [0.8        0.75       0.28571429]]
[[5 0 0]
 [4 3 2]]
[[ 15625 823543    729]
 [  1024     81    128]]


In [ ]:
import numpy as np

x=np.array([
    [25,5000,60,2],
    [30,6000,75,5],
    [np.nan,55000,68,3],
    [40,np.nan,80,10],
    [35,7000,np.nan,6],
    [28,52000,65,2],
    [45,900000,85,12],
    [32,58000,70,np.nan],
    [50,120000, 95,15],
    [27,51000,62,1]
])

y=np.array([0,1,0,1,1,0,1,0,1,0])

print(x.shape)
print(x.dtype)
print(x.ndim)
print(x.size)
print(np.isnan(x))
print(np.isnan(x).sum(axis=0))
col_means=(np.nanmean(x,axis=0))
print(col_means)
rows,cols=np.where(np.isnan(x))
print(rows,cols)


x[rows,cols] = col_means[cols]
print(x)

print(x[:3])
print(x[6:9])


In [ ]:
#boolean indexing

x=np.array([
    [25,5000,60,2],
    [30,6000,75,5],
    [np.nan,55000,68,3],
    [40,np.nan,80,10],
    [35,7000,np.nan,6],
    [28,52000,65,2],
    [45,900000,85,12],
    [32,58000,70,np.nan],
    [50,120000, 95,15],
    [27,51000,62,1]
])

print(x[x[:,1]>60000])



In [ ]:
c=np.array([
    [[1,2,4,5],[2,3,4,5],[2,1,3,2]],
    [[3,4,5,6],[1,2,3,4,],[4,5,6,7]]
])

d=np.array([
    [[1,2,3,4],[1,2,4,5],[4,5,6,7]],
    [[1,5,6,7],[5,6,7,8],[6,5,4,3]]
])

print(np.add(c,d))
print(np.subtract(c,d))
print(np.multiply(c,d))
print(np.divide(c,d))
print(np.mod(c,d))
print(np.power(c,d))


[[[ 2  4  7  9]
  [ 3  5  8 10]
  [ 6  6  9  9]]

 [[ 4  9 11 13]
  [ 6  8 10 12]
  [10 10 10 10]]]
[[[ 0  0  1  1]
  [ 1  1  0  0]
  [-2 -4 -3 -5]]

 [[ 2 -1 -1 -1]
  [-4 -4 -4 -4]
  [-2  0  2  4]]]
[[[ 1  4 12 20]
  [ 2  6 16 25]
  [ 8  5 18 14]]

 [[ 3 20 30 42]
  [ 5 12 21 32]
  [24 25 24 21]]]
[[[1.         1.         1.33333333 1.25      ]
  [2.         1.5        1.         1.        ]
  [0.5        0.2        0.5        0.28571429]]

 [[3.         0.8        0.83333333 0.85714286]
  [0.2        0.33333333 0.42857143 0.5       ]
  [0.66666667 1.         1.5        2.33333333]]]
[[[0 0 1 1]
  [0 1 0 0]
  [2 1 3 2]]

 [[0 4 5 6]
  [1 2 3 4]
  [4 0 2 1]]]
[[[     1      4     64    625]
  [     2      9    256   3125]
  [    16      1    729    128]]

 [[     3   1024  15625 279936]
  [     1     64   2187  65536]
  [  4096   3125   1296    343]]]


In [ ]:
#scalar product
print(np.add(a,5))
print(np.subtract(a,4))
print(np.multiply(a,5))
print(np.divide(a,5))
print(np.mod(a,3))

print(np.sqrt(a))
print(np.square(a))
print(np.exp(a))
print(np.log(a))
print(np.log10(a))

#trigonometric functions
angles=np.array([0,np.pi/2, np.pi])
print(angles)
print(np.sin(angles))
print(np.cos(angles))
print(np.tan(angles))

#rounding and absolute functions
x=np.array([1.2,2.7,-3.5])
print(np.round(x))
print(np.floor(x))
print(np.ceil(x))
print(np.abs(x))


[[10 12 14]
 [ 9  8  7]]
[[ 1  3  5]
 [ 0 -1 -2]]
[[25 35 45]
 [20 15 10]]
[[1.  1.4 1.8]
 [0.8 0.6 0.4]]
[[2 1 0]
 [1 0 2]]
[[2.23606798 2.64575131 3.        ]
 [2.         1.73205081 1.41421356]]
[[25 49 81]
 [16  9  4]]
[[1.48413159e+02 1.09663316e+03 8.10308393e+03]
 [5.45981500e+01 2.00855369e+01 7.38905610e+00]]
[[1.60943791 1.94591015 2.19722458]
 [1.38629436 1.09861229 0.69314718]]
[[0.69897    0.84509804 0.95424251]
 [0.60205999 0.47712125 0.30103   ]]
[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[ 1.  3. -4.]
[ 1.  2. -4.]
[ 2.  3. -3.]
[1.2 2.7 3.5]


In [ ]:
#mean and median

data=np.array([10,20,30,40,50])
print(np.median(data))

#variance and standard deviation
print(np.var(data))
print(np.std(data))

#minimum maximum and range
print(np.min(data))
print(np.max(data))
print(np.ptp(data))

#sum and cummulative sum
print(np.sum(data))
print(np.cumsum(data))

#axis-based operations
arr=np.array([[1,2,3],
              [4,5,6]])

#column wise
print(np.sum(arr,axis=0))
print(np.mean(arr,axis=0))

#row wise
print(np.sum(arr,axis=1))
print(np.mean(arr,axis=1))

#random no function
print(np.random.rand(5))
print(np.random.randn(5))
print(np.random.randint(1,10,5))

#corelation and covariance
x=np.array([1,2,3,4,5])
y=np.array([5,4,3,2,1])
print(np.corrcoef(x,y))
print(np.cov(x,y))

#sorting and indexing  function

arr=np.array([3,1,4,2])
print(np.sort(arr))
print(np.argmax(arr))
print(np.argmin(arr))

[1 2 3 4]
2
1
